spring.application.name=SpringBootSecurityPostgresqlApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/music_api_final?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=teleios

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# App Properties
bezkoder.app.jwtSecret= iloveadsoftsitoiloveadsoftsitoiloveadsoftsito
bezkoder.app.jwtExpirationMs=86400000
